### ISSUE TITLE
Remove dependency on GNUMakefile

### ISSUE THREAD

**Issue by gedw99** [aperturerobotics/protobuf-project#2]
Makefile:13: *** missing separator.  Stop.Makefile:13: *** missing separator.  Stop.

**Comment by paralin** [comment]
Should be fine! You need GNU Make.

**Comment by gedw99** [comment]
ah mac version is not standard..

ok

**Comment by paralin** [comment]
@gedw99 I'm interested in replacing the makefiles with Mage (pure go make) or maybe just a custom project CLI. Is this something you could help with? It would significantly improve adoption since these projects would then no longer depend on gnu make.

**Comment by paralin** [comment]
If you look at all the aperturerobotics projects they share roughly identical makefiles. The tool would have a urfave/cli with commands for each target

**Comment by gedw99** [comment]
Can me playing with mage again. See what you think...

Am thnking about combine with gotasks for the final high level file, because magefiles are too laborious at the top level.

you can run the mage file at 3 level.
mage (mage installed )
code ( go installed )
binary ( the magefiles compiled  )

```

# https://github.com/aserto-dev/mage-loot

# All works well


REPO_NAME=mage-loot

BIN_NAME=static-output

print:

dep-git:
	git clone git@github.com:aserto-dev/mage-loot.git
	@echo $(REPO_NAME) >> .gitignore

dep-tools:
	go install github.com/magefile/mage@latest
dep-tools-delete:
	rm -f $(shell which mage)

dep-git-delete:
	rm -rf $(REPO_NAME)

mod:
	cd $(REPO_NAME) && go mod tidy
	cd $(REPO_NAME) && go mod verify

## THIS - only works if compiled. Use go-compile first :)

# Override this is you want 
RUN_TARGET=??
this-dep: go-compile

this-run:
	# make RUN_TARGET=-l this-run
	cd $(REPO_NAME)/magefiles && ./static-output $(RUN_TARGET)
this-help: this-dep
	cd $(REPO_NAME)/magefiles && ./static-output -h
this-list:
	cd $(REPO_NAME)/magefiles && ./static-output -l

this-deps:
	cd $(REPO_NAME)/magefiles && ./static-output -h deps
	cd $(REPO_NAME)/magefiles && ./static-output -v deps
this-lint:
	cd $(REPO_NAME)/magefiles && ./static-output -h lint
	cd $(REPO_NAME)/magefiles && ./static-output -v lint


## GO - only works in go installed

# Override this is you want 
RUN_TARGET=??
go-run:
	# make RUN_TARGET=-l go-run
	cd $(REPO_NAME) && go run mage.go $(RUN_TARGET)
go-list:
	cd $(REPO_NAME) && go run mage.go -l
go-deps:
	cd $(REPO_NAME) && go run mage.go deps
go-lint:
	cd $(REPO_NAME) && go run mage.go lint
go-test:
	cd $(REPO_NAME) && go run mage.go test
go-compile:
	cd $(REPO_NAME) && go run mage.go -compile ./$(BIN_NAME)
go-compile-delete:
	rm -f $(REPO_NAME)/magefiles/$(BIN_NAME)


### MAGE - only works if mage installed. Just needed this to test higher level this. Dont need it.

mage-list:
	cd $(REPO_NAME) && mage -l
mage-run:
	cd $(REPO_NAME) && mage $(RUN_TARGET)
mage-compile:
	cd $(REPO_NAME) && mage -compile ./static-output

```

**Comment by paralin** [comment]
@gedw99 I think it makes sense actually to just go the CLI route:

 - Embed the hack/ directory with go:embed
 - When running the dev cli, checkout hack/ to .go/protobuf-project/
 - Add cli commands which exec "go run" inside the .go/protobuf-project/ dir.

... basically just copying all the bash commands from Makefile into https://pkg.go.dev/os/exec commands

**Comment by gedw99** [comment]
sure that possible.

But did you study what that mage project does ?

https://www.aserto.com/blog/mage-loot-dependency-management-for-go

- does binary deps for you with multiversioning
- does multi targets builds and releases
- is used by all their other projects. https://github.com/aserto-dev/mage-loot/network/dependents

**Comment by gedw99** [comment]
and it can also call exec of course :)

**Comment by paralin** [comment]
Out of scope for now :)
